apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: node-example
  namespace: default
spec:
  scaleTargetRef:
    apiVersion: extensions/v1
    kind: Deployment
    name: node-example
  maxReplicas: 4
  minReplicas: 1
  targetCPUUtilizationPercentage: 50
